apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: load-webpage
  namespace: default
spec:
  revisionHistoryLimit: 3
  replicas: 2
  selector:
    matchLabels:
      app: load-webpage
  template:
    metadata:
      labels:
        app: load-webpage
    spec:
      containers:
      - name: load-webpage
        image: registry.gitlab.com/sellcom/load_webpage:PROD_VERSION
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: registry.gitlab.com
---
apiVersion: v1
kind: Service
metadata:
  name: load-webpage
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: load-webpage
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: load-webpage
  annotations:
    kubernetes.io/ingress.global-static-ip-name: load-webpage
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: load-secure
  backend:
    serviceName: load-webpage
    servicePort: 80
